remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: HYPERLATTICE
description: Algebraic Lattice, Hyperlattice, and Probabilistic Hyperlattice
  Library for Common Lisp
author: "the Phoeron" Colin J.E. Lupton
logo: /assets/images/hyperlattice-logo-gothic.png
