remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: HYPERLATTICES
description: Generalized Lattice data-types for Common Lisp, including Algebraic Lattices, Hyperlattices, and Probabilistic Hyperlattices, which intends to follow the packages-as-types convention.
logo: /assets/images/hyperlattice-logo-gothic.png
